---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bloodbank-statefulset
spec:
  serviceName: "bloodbank-service"
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: "mysqldb"
        image: shaikmustafa/mybloodbank:db
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: bloodbank-cm
        - secretRef:
            name: bloodbank-secret
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi